package com.jugendteam_whv.Spielekartei

enum class Category {
    GROUP_ALLOCATION, GET_TO_KNOW, CIRCLE_GAME, SINGING_GAME, MOVEMENT_GAME, TERRAIN_GAME, TRUST_GAME, PRAYERS, IMPETUS, PUZZLE, DEFAULT
}