name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: List APK outputs
      run: ls -R app/build/outputs/apk
    - name: Grant read write permission for .apk
      run: chmod +rw app/build/outputs/apk/release/app-release-unsigned.apk
    - name: Rename APK
      run: app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/Jugendteam_Spielekartei.apk
  
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-apk
        path: app/build/outputs/apk/release/Jugendteam_Spielekartei.apk

